INSERT INTO "Product" (
  "id",
  "name",
  "photos",
  "calories",
  "proteins",
  "fats",
  "carbs",
  "compositionText",
  "category",
  "preparationType",
  "isVegan",
  "isGlutenFree",
  "isSugarFree",
  "updatedAt"
) VALUES
  (
    'seed_beet',
    'Свёкла',
    ARRAY['/data/svekla.png']::TEXT[],
    43,
    1.6,
    0.2,
    9.6,
    'Свежая свёкла',
    'Vegetables',
    'RequiresCooking',
    true,
    true,
    true,
    CURRENT_TIMESTAMP
  ),
  (
    'seed_potato',
    'Картофель',
    ARRAY['/data/potatoes.png']::TEXT[],
    77,
    2,
    0.4,
    16.3,
    'Свежий картофель',
    'Vegetables',
    'RequiresCooking',
    true,
    true,
    true,
    CURRENT_TIMESTAMP
  ),
  (
    'seed_water',
    'Вода',
    ARRAY['/data/water.png']::TEXT[],
    0,
    0,
    0,
    0,
    'Питьевая вода',
    'Liquid',
    'ReadyToEat',
    true,
    true,
    true,
    CURRENT_TIMESTAMP
  ),
  (
    'seed_meat',
    'Мясо',
    ARRAY['/data/meat.jpeg', '/data/meat2.jpeg']::TEXT[],
    187.2,
    18.9,
    12.4,
    0,
    'Говядина',
    'Meat',
    'RequiresCooking',
    false,
    true,
    true,
    CURRENT_TIMESTAMP
  ),
  (
    'seed_pumpkin',
    'Тыква',
    ARRAY['/data/pumpkin.png']::TEXT[],
    26,
    1,
    0.1,
    6.5,
    'Тыква свежая',
    'Vegetables',
    'RequiresCooking',
    true,
    true,
    true,
    CURRENT_TIMESTAMP
  ),
  (
    'seed_donuts',
    'Пончики',
    ARRAY['/data/donuts.png']::TEXT[],
    452,
    4.9,
    25,
    51,
    'Пончики классические',
    'Sweets',
    'ReadyToEat',
    false,
    false,
    false,
    CURRENT_TIMESTAMP
  );

INSERT INTO "Dish" (
  "id",
  "name",
  "photos",
  "calories",
  "proteins",
  "fats",
  "carbs",
  "portionSize",
  "category",
  "isVegan",
  "isGlutenFree",
  "isSugarFree",
  "updatedAt"
) VALUES
  (
    'seed_borsch',
    'Борщ',
    ARRAY['/data/borsch.png']::TEXT[],
    0,
    0,
    0,
    0,
    450,
    'Soup',
    false,
    true,
    true,
    CURRENT_TIMESTAMP
  ),
  (
    'seed_borsch_vegan',
    'Борщ веганский',
    ARRAY['/data/borsch_vegan.png']::TEXT[],
    0,
    0,
    0,
    0,
    450,
    'Soup',
    true,
    true,
    true,
    CURRENT_TIMESTAMP
  ),
  (
    'seed_potato_pohlebka',
    'Похлёбка картофельная',
    ARRAY[]::TEXT[],
    0,
    0,
    0,
    0,
    700,
    'Soup',
    true,
    true,
    true,
    CURRENT_TIMESTAMP
  );

INSERT INTO "DishIngredient" ("dishId", "productId", "grams") VALUES
  ('seed_borsch', 'seed_beet', 120),
  ('seed_borsch', 'seed_potato', 180),
  ('seed_borsch', 'seed_water', 300),
  ('seed_borsch', 'seed_meat', 150),
  ('seed_borsch_vegan', 'seed_beet', 120),
  ('seed_borsch_vegan', 'seed_potato', 180),
  ('seed_borsch_vegan', 'seed_water', 320),
  ('seed_potato_pohlebka', 'seed_potato', 200),
  ('seed_potato_pohlebka', 'seed_water', 500);